//! Sealing what travels between wallets: addresses and payment bundles.
//!
//! **Hybrid ML-KEM-768 + X25519.** Both key exchanges run, both shared secrets
//! feed one HKDF, and the result keys a ChaCha20-Poly1305 seal. An attacker
//! must break *both* to read the message: ML-KEM covers the quantum adversary
//! harvesting traffic today to decrypt later, X25519 covers the possibility
//! that ML-KEM has a classical flaw we do not know about yet. Neither alone is
//! trusted.
//!
//! ## Why lattice cryptography is allowed here
//!
//! The locked rule (`SPEC.md` §3) is *hashes only on the money path*. This is not
//! the money path. Nothing an envelope carries can authorize a spend: the
//! coin's owner key is a hash-based one-time key generated by the payee, and
//! the spend anchor means even the payer cannot compute a coin's nullifier
//! (`SPEC.md` §6). Break the envelope entirely and you learn who paid whom what —
//! a real loss, and strictly a privacy one. **A lattice break must never move
//! money, and here it cannot.**
//!
//! ## What the receiver has to do
//!
//! Trial-decapsulation: try to open each envelope you are handed. Success
//! means it was for you. There is no per-message identifier to match on,
//! because an identifier is exactly the metadata the design refuses to leak.
//!
//! Keys derive from the wallet seed, so a restored wallet can decrypt its own
//! history without extra backup material.

use chacha20poly1305::aead::{Aead, KeyInit};
use chacha20poly1305::{ChaCha20Poly1305, Key, Nonce};
use hkdf::Hkdf;
use ml_kem::array::Array;
use ml_kem::ml_kem_768::{DecapsulationKey, EncapsulationKey};
use ml_kem::{Decapsulate, KeyExport, Seed};
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use x25519_dalek::{PublicKey as XPublic, StaticSecret as XSecret};

/// Domain separation for the HKDF, so this key schedule can never collide with
/// another use of the same secrets.
const HKDF_INFO: &[u8] = b"ultraviolet/envelope/v1/mlkem768+x25519";

/// The public half of a scan key: what an address publishes.
#[derive(Clone, Serialize, Deserialize)]
pub struct ScanPublic {
    pub ml_kem_hex: String,
    pub x25519_hex: String,
}

/// The secret half. Derived from the wallet seed, never transmitted.
pub struct ScanSecret {
    ml_kem: DecapsulationKey,
    x25519: XSecret,
}

/// A sealed message. The two key-exchange ciphertexts are not the payload; `ct`
/// is.
///
/// Raw bytes rather than hex strings. This travels as a chat attachment, and
/// hex would double every byte on the wire for no benefit — nothing reads these
/// by eye. Serialize it with a binary encoder; JSON would undo the saving by
/// writing each byte as a decimal number.
#[derive(Clone, Serialize, Deserialize)]
pub struct Sealed {
    pub ml_kem_ct: Vec<u8>,
    pub x25519_eph: Vec<u8>,
    pub nonce: Vec<u8>,
    pub ct: Vec<u8>,
}

#[derive(Debug, PartialEq, Eq)]
pub enum OpenError {
    /// Not addressed to this key, or altered in flight. Deliberately one
    /// error: an authenticated cipher cannot distinguish them, and a receiver
    /// doing trial-decapsulation must not learn which.
    NotForMe,
    Malformed,
}

fn urandom<const N: usize>() -> [u8; N] {
    use std::io::Read;
    let mut b = [0u8; N];
    std::fs::File::open("/dev/urandom")
        .expect("urandom")
        .read_exact(&mut b)
        .expect("read urandom");
    b
}

/// Expand a wallet seed into a scan keypair.
///
/// Both halves come from the same seed under different domain tags, so "write
/// down the seed" still restores the ability to read your own mail.
pub fn derive_scan(wallet_seed: &[u8; 32]) -> (ScanSecret, ScanPublic) {
    let hk = Hkdf::<Sha256>::new(Some(b"ultraviolet/scan/v1"), wallet_seed);

    let mut kem_seed = [0u8; 64];
    hk.expand(b"ml-kem-768", &mut kem_seed)
        .expect("64 bytes from hkdf");
    let ml_kem = DecapsulationKey::from_seed(Seed::from(kem_seed));

    let mut x_seed = [0u8; 32];
    hk.expand(b"x25519", &mut x_seed)
        .expect("32 bytes from hkdf");
    let x25519 = XSecret::from(x_seed);

    let public = ScanPublic {
        ml_kem_hex: hex::encode(ml_kem.encapsulation_key().to_bytes()),
        x25519_hex: hex::encode(XPublic::from(&x25519).as_bytes()),
    };
    (ScanSecret { ml_kem, x25519 }, public)
}

/// Combine the two shared secrets into one AEAD key. Both are mixed in, so the
/// key is only as weak as the *stronger* of the two exchanges.
fn combine(kem_ss: &[u8], x_ss: &[u8], kem_ct: &[u8], x_eph: &[u8]) -> [u8; 32] {
    let mut ikm = Vec::with_capacity(kem_ss.len() + x_ss.len() + kem_ct.len() + x_eph.len());
    ikm.extend_from_slice(kem_ss);
    ikm.extend_from_slice(x_ss);
    // The transcript is bound in too, so a key cannot be reused under a
    // different exchange.
    ikm.extend_from_slice(kem_ct);
    ikm.extend_from_slice(x_eph);
    let hk = Hkdf::<Sha256>::new(None, &ikm);
    let mut key = [0u8; 32];
    hk.expand(HKDF_INFO, &mut key).expect("32 bytes from hkdf");
    key
}

/// Seal `plaintext` to a published scan key.
pub fn seal(to: &ScanPublic, plaintext: &[u8]) -> Result<Sealed, OpenError> {
    let kem_pk_bytes = hex::decode(&to.ml_kem_hex).map_err(|_| OpenError::Malformed)?;
    // `Array` is length-typed: a wrong-sized key is rejected here rather than
    // panicking deeper in.
    let kem_pk = Array::try_from(kem_pk_bytes.as_slice()).map_err(|_| OpenError::Malformed)?;
    let ek = EncapsulationKey::new(&kem_pk).map_err(|_| OpenError::Malformed)?;
    let x_pk_bytes: [u8; 32] = hex::decode(&to.x25519_hex)
        .map_err(|_| OpenError::Malformed)?
        .try_into()
        .map_err(|_| OpenError::Malformed)?;

    // ML-KEM half. Deterministic encapsulation with our own entropy, so this
    // does not depend on which `rand_core` generation the crate wants.
    let m: [u8; 32] = urandom();
    let (kem_ct, kem_ss) = ek.encapsulate_deterministic(&m.into());

    // X25519 half, ephemeral: a fresh sender key per message means two
    // messages to the same payee share nothing an observer can link.
    let eph = XSecret::from(urandom::<32>());
    let x_ss = eph.diffie_hellman(&XPublic::from(x_pk_bytes));
    let x_eph_pub = XPublic::from(&eph);

    let kem_ct_bytes: &[u8] = kem_ct.as_slice();
    let key = combine(&kem_ss, x_ss.as_bytes(), kem_ct_bytes, x_eph_pub.as_bytes());
    let nonce: [u8; 12] = urandom();
    let ct = ChaCha20Poly1305::new(Key::from_slice(&key))
        .encrypt(Nonce::from_slice(&nonce), plaintext)
        .map_err(|_| OpenError::Malformed)?;

    Ok(Sealed {
        ml_kem_ct: kem_ct_bytes.to_vec(),
        x25519_eph: x_eph_pub.as_bytes().to_vec(),
        nonce: nonce.to_vec(),
        ct,
    })
}

/// Try to open a sealed message. `NotForMe` covers both "addressed to someone
/// else" and "tampered with" — see [`OpenError`].
pub fn open(secret: &ScanSecret, sealed: &Sealed) -> Result<Vec<u8>, OpenError> {
    let kem_ct = sealed.ml_kem_ct.clone();
    let x_eph: [u8; 32] = sealed
        .x25519_eph
        .as_slice()
        .try_into()
        .map_err(|_| OpenError::Malformed)?;
    let nonce = sealed.nonce.clone();
    let ct = sealed.ct.clone();
    if nonce.len() != 12 {
        return Err(OpenError::Malformed);
    }

    // ML-KEM decapsulation never fails by design: a ciphertext meant for
    // someone else yields a different shared secret, not an error. The AEAD
    // tag is what actually decides, which is exactly what makes trial
    // decapsulation constant-shaped.
    let kem_ct_arr = Array::try_from(kem_ct.as_slice()).map_err(|_| OpenError::Malformed)?;
    let kem_ss = secret.ml_kem.decapsulate(&kem_ct_arr);
    let x_ss = secret.x25519.diffie_hellman(&XPublic::from(x_eph));

    let key = combine(&kem_ss, x_ss.as_bytes(), &kem_ct, &x_eph);
    ChaCha20Poly1305::new(Key::from_slice(&key))
        .decrypt(Nonce::from_slice(&nonce), ct.as_ref())
        .map_err(|_| OpenError::NotForMe)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seals_and_opens() {
        let (sk, pk) = derive_scan(&[1u8; 32]);
        let s = seal(&pk, b"a payment bundle").unwrap();
        assert_eq!(open(&sk, &s).unwrap(), b"a payment bundle");
    }

    #[test]
    fn someone_elses_mail_does_not_open() {
        let (_, pk_a) = derive_scan(&[1u8; 32]);
        let (sk_b, _) = derive_scan(&[2u8; 32]);
        let s = seal(&pk_a, b"for alice").unwrap();
        assert_eq!(open(&sk_b, &s), Err(OpenError::NotForMe));
    }

    #[test]
    fn tampering_is_caught() {
        let (sk, pk) = derive_scan(&[3u8; 32]);
        let mut s = seal(&pk, b"secret").unwrap();
        s.ct[0] ^= 1;
        assert_eq!(open(&sk, &s), Err(OpenError::NotForMe));
    }

    /// The hybrid has to be a real hybrid: swapping in a different X25519
    /// ephemeral must break the key even though the ML-KEM half is untouched.
    /// If this passed, the X25519 leg would be decorative.
    #[test]
    fn both_halves_are_load_bearing() {
        let (sk, pk) = derive_scan(&[4u8; 32]);
        let a = seal(&pk, b"m").unwrap();
        let b = seal(&pk, b"m").unwrap();

        let mut kem_from_a = a.clone();
        kem_from_a.x25519_eph = b.x25519_eph.clone();
        assert_eq!(open(&sk, &kem_from_a), Err(OpenError::NotForMe));

        let mut x_from_a = a.clone();
        x_from_a.ml_kem_ct = b.ml_kem_ct.clone();
        assert_eq!(open(&sk, &x_from_a), Err(OpenError::NotForMe));
    }

    #[test]
    fn the_same_message_seals_differently_every_time() {
        // Otherwise an observer could tell that two payments carry identical
        // contents, which is metadata the design refuses to leak.
        let (_, pk) = derive_scan(&[5u8; 32]);
        let a = seal(&pk, b"same").unwrap();
        let b = seal(&pk, b"same").unwrap();
        assert_ne!(a.ct, b.ct);
        assert_ne!(a.ml_kem_ct, b.ml_kem_ct);
        assert_ne!(a.x25519_eph, b.x25519_eph);
    }

    #[test]
    fn scan_keys_restore_from_the_wallet_seed() {
        let (_, a) = derive_scan(&[6u8; 32]);
        let (_, b) = derive_scan(&[6u8; 32]);
        assert_eq!(a.ml_kem_hex, b.ml_kem_hex);
        assert_eq!(a.x25519_hex, b.x25519_hex);
        let (_, c) = derive_scan(&[7u8; 32]);
        assert_ne!(a.ml_kem_hex, c.ml_kem_hex);
    }
}
